### ISSUE TITLE
Damage Macro

### ISSUE THREAD

**Issue by itteerde** [itteerde/ep2eFVTT#1]
1. Select Token/s for whom the Actor is to be damaged (if there are multiple Tokens for the same Actor that Actor would be dealt damage times number of Tokens).
2. Execute Macro.
3. Macro deals damage (directly, reduction such as Armor is done before using the Macro).
4. Report who was dealt what amount of damage in Chat in a form as short as possible (one-liner preferred).

**Comment by itteerde** [comment]
We have two types of damage. Can we use the Icons from `dnd-tablerules` (you just putting them appart and practice)? Do we need new Icons? Do we have other Icons?

![image](https://github.com/itteerde/ep2eFVTT/assets/8367477/0103321b-92a0-4edd-bdcf-87ce92090221)

**Comment by itteerde** [comment]
![image](https://github.com/itteerde/ep2eFVTT/assets/8367477/8a9da6e2-972e-44d0-9ce7-2abc8b0b85c6)

Works, but if one wants to assign bad numbers (or does composition by our denominations badly) or different numbers to different Actors (which would be the standard for AoE I'd think because Armor) it gets pretty chatty. Suggest we test and discuss.

**Comment by itteerde** [comment]
If one is dumb and has the Actor out twice (well make the Tokens distinguishable) it will report twice in Chat, but deal damage only once (in testing that is -- I think there should be room for a race condition somewhere).

**Comment by itteerde** [comment]
Is the damage (almost) always reduced by Armor? If so (as we have the value anyways) that could be included in the Macro, and I think if it is just subtracting and Min(that, 0) or something similarily trivial that would be simple.

**Comment by PhDaveMil** [comment]
I don't think we need healing. That seems like something that happens rarely enough that it should just be handled manually, without a macro.

**Comment by itteerde** [comment]
Should there be a Dialog it needs to account for AP Ammo (halfs/Armor).

**Comment by itteerde** [comment]
Right-clicking the ChatCard is only "mightly preferred" by @PhDaveMil

**Comment by PhDaveMil** [comment]
Slightly, or mildly. :P

**Comment by itteerde** [comment]
Pack into Compendium using the white heart.

**Comment by itteerde** [comment]
done
