### ISSUE TITLE
Report Dialog Macro GM

### ISSUE THREAD

**Issue by itteerde** [itteerde/ep2eFVTT#2]
### Data Model

| concept |  key | notes | state |
| --- | --- | --- | --- |
| health damage | `system.health.physical.value` | | |
| durability | `system.health.physical.max` | | |
| death threshold | `system.physical.dr` | | |
| wounds | `system.physical.wounds` | | |
| wound threshold | `system.physical.wt` | | |
| mental stress | `system.health.mental.value` | | |
| lucidity |  `system.health.mental.max`| | |
| insanity rating | `system.mental.ir` | | |
| traumata | `system.mental.trauma` | | |
| trauma treshhold | `system.mental.tt` | | |
| armor energy | `system.physical.energyArmorTotal` | | |
| armor kinetic | `system.physical.kineticArmorTotal` | | |

✅❌⌛

### Icons

Need to be included in Module for robustness.

| icon | font-awsome | path | notes | state |
| --- | --- | --- | --- | --- |
| Heart | `<i class="fa-solid fa-heart-pulse awesomeIcon" style="font-size: 18px;"></i>` | | | |
| Bandage | `<i class="fa-regular fa-bandage awesomeIcon" style="font-size: 18px;"></i>` | | | |
| Brain | `<i class="fa-solid fa-brain awesomeIcon" style="font-size: 18px;"></i>` | | | |
| Blast | `<i class="fa-regular fa-burst awesomeIcon" style="font-size: 18px;"></i>` | | | |
| Lightning | | `<ours>/power.webp` | | |
| Shield | | `<ours>/shield.webp` | | |

**Comment by itteerde** [comment]
![image](https://github.com/itteerde/ep2eFVTT/assets/8367477/d764ad2b-430e-4327-9991-7a4573faa7a7)

**Comment by PhDaveMil** [comment]
It would be nice if it captured the following information too:

![image](https://github.com/itteerde/ep2eFVTT/assets/148652003/44b76d3b-ae2f-4c81-9a30-7f622e9197df)

**Comment by itteerde** [comment]
```js
canvas.tokens.controlled[0].actor.system.physical

{
    "wounds": null,
    "damage": null,
    "dr": 80,
    "wt": 8,
    "min": 0,
    "energyArmorTotal": 0,
    "kineticArmorTotal": 0,
    "mainArmorTotal": 0,
    "additionalArmorTotal": 0,
    "mainArmorMalus": 0,
    "additionalArmorMalus": 0,
    "armorMalusTotal": 0,
    "armorSomMalus": 0,
    "armorDurAnnounce": "",
    "totalWeaponMalus": 0,
    "totalGearMalus": 0
}
```

**Comment by itteerde** [comment]
```js
canvas.tokens.controlled[0].actor.system.mental

{
    "trauma": null,
    "stress": null,
    "luc": null,
    "ir": 60,
    "tt": 6,
    "min": 0
}
```

**Comment by itteerde** [comment]
```js
canvas.tokens.controlled[0].actor.system.health

{
    "physical": {
        "value": 11,
        "max": 40
    },
    "mental": {
        "value": 0,
        "max": 30
    },
    "death": {
        "value": 0,
        "max": 40
    },
    "insanity": {
        "value": 0,
        "max": 30
    }
}
```

**Comment by Taseabridge** [comment]
<i class="fa-solid fa-heart-pulse awesomeIcon" style="font-size: 18px;"></i>
<i class="fa-regular fa-bandage awesomeIcon" style="font-size: 18px;"></i>
<i class="fa-solid fa-brain awesomeIcon" style="font-size: 18px;"></i>
<i class="fa-regular fa-burst awesomeIcon" style="font-size: 18px;"></i>
<i class="fa-regular fa-stopwatch awesomeIcon" style="font-size: 18px;"></i>

**Comment by itteerde** [comment]
![image](https://github.com/itteerde/ep2eFVTT/assets/8367477/da8b6d56-35ec-4792-869d-1778359cc8ae)

* A(E) will be the Lightning Icon
* A(K) will be the Shield Icon

done?

**Comment by itteerde** [comment]
![image](https://github.com/itteerde/ep2eFVTT/assets/8367477/351bcc03-23cb-42cf-96b9-8a69c367fd5b)
![image](https://github.com/itteerde/ep2eFVTT/assets/8367477/70445bec-5510-43da-85f7-6879d374a490)

Should we put them into a grid, and if so is that needed urgently, or is this readable enough for the time being?

**Comment by PhDaveMil** [comment]
This is good enough for me.
